"use client";
import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, Bot, BrainCircuit, Check, ChevronDown, Code2, Database, Globe2, Menu, MessageSquareText, Mic2, Moon, Network, PhoneCall, Smartphone, Sparkles, Sun, Workflow, X, Zap } from "lucide-react";
import { SparkVLogo } from "@/components/sparkv-logo";

const services = [
  [Code2,"01","Software Development","Web products, SaaS platforms, internal tools, APIs, and backend systems engineered to last.",["Web apps","SaaS","APIs"]],
  [Smartphone,"02","Mobile Development","Purpose-built iOS, Android, and cross-platform experiences backed by resilient systems.",["iOS","Android","Cross-platform"]],
  [BrainCircuit,"03","AI & Automation","AI copilots, RAG, document intelligence, and workflows connected to the tools you already use.",["RAG","Workflows","AI systems"]],
  [Bot,"04","AI Agents","Specialized agents that research, support, qualify, coordinate, and execute with human oversight.",["Sales","Support","Research"]],
  [Mic2,"05","Voice AI","Natural voice agents for reception, qualification, scheduling, and customer operations.",["Inbound","Outbound","Support"]],
  [MessageSquareText,"06","Social AI","Intelligent content, publishing, engagement, and lead workflows without brittle busywork.",["Content","Leads","Publishing"]],
] as const;
const agents = [
  ["Sales Agent",Zap,["Lead captured","Account researched","Qualified","CRM updated","Follow-up drafted"]],
  ["Research Agent",BrainCircuit,["Brief received","Sources searched","Evidence ranked","Findings synthesized","Report delivered"]],
  ["Support Agent",MessageSquareText,["Request understood","Context retrieved","Action selected","Issue resolved","Record updated"]],
  ["Voice Agent",PhoneCall,["Call connected","Intent detected","Tools invoked","Appointment booked","Summary sent"]],
] as const;
const process = [["01","Discover","We map the business goal, constraints, users, and systems before choosing the technology."],["02","Design","We turn the problem into a clear product and technical architecture."],["03","Build","Small, testable releases keep quality visible and decisions reversible."],["04","Integrate","We connect data, APIs, AI models, and the tools your team already relies on."],["05","Launch","Production readiness includes security, observability, performance, and handoff."],["06","Improve","We learn from real usage, remove friction, and extend what creates value."]];
function SectionIntro({label,title,body}:{label:string;title:string;body?:string}){return <div className="section-intro"><p className="section-label"><span/>{label}</p><h2>{title}</h2>{body&&<p>{body}</p>}</div>}

export function Homepage(){
 const [dark,setDark]=useState(true),[menu,setMenu]=useState(false),[agent,setAgent]=useState(0),[formStep,setFormStep]=useState(0),[sent,setSent]=useState(false);
 useEffect(()=>{const s=localStorage.getItem("sparkv-theme"),v=s?s==="dark":matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.dataset.theme=v?"dark":"light";queueMicrotask(()=>setDark(v))},[]);
 const toggleTheme=()=>{const v=!dark;setDark(v);localStorage.setItem("sparkv-theme",v?"dark":"light");document.documentElement.dataset.theme=v?"dark":"light"};
 return <main>
  <header className="site-header"><a href="#top" className="brand" aria-label="SparkV home"><SparkVLogo/></a><nav className="desktop-nav"><a href="#services">Services</a><a href="#systems">Systems</a><a href="#work">Work</a><a href="#process">Process</a><a href="#about">About</a></nav><div className="header-actions"><button className="icon-button" onClick={toggleTheme} aria-label={dark?"Switch to light theme":"Switch to dark theme"}>{dark?<Sun size={16}/>:<Moon size={16}/>}</button><a href="#contact" className="header-cta">Start a project <ArrowUpRight size={15}/></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div><div className={`mobile-menu ${menu?"open":""}`}>{["services","systems","work","process","about","contact"].map(x=><a key={x} href={`#${x}`} onClick={()=>setMenu(false)}>{x[0].toUpperCase()+x.slice(1)}</a>)}</div></header>
  <section id="top" className="hero"><div className="hero-grid"/><div className="hero-glow"/><div className="hero-copy"><p className="eyebrow"><span/> SPARKV / SOFTWARE × AI × AUTOMATION</p><h1>We build software that moves businesses <em>forward.</em></h1><p className="hero-lede">From web and mobile products to AI agents, voice systems, and intelligent automation—SparkV turns complex ideas into production-ready technology.</p><div className="hero-actions"><a href="#contact" className="button button-primary">Start a Project <ArrowUpRight size={18}/></a><a href="#services" className="button button-ghost">Explore What We Build <ChevronDown size={17}/></a></div></div><div className="system-stage"><div className="stage-topline"><span>SYSTEM / ONLINE</span><span>01:24:08</span></div><div className="system-ring ring-one"/><div className="system-ring ring-two"/><div className="system-core"><span>V</span><small>ORCHESTRATOR</small></div>{[["PRODUCT","Interface layer","node-product"],["INTELLIGENCE","Agent network","node-intel"],["AUTOMATION","Workflow engine","node-auto"],["OUTCOME","Business impact","node-outcome"]].map(x=><div key={x[0]} className={`system-node ${x[2]}`}><i/>{x[0]}<small>{x[1]}</small></div>)}<svg className="system-lines" viewBox="0 0 640 500" preserveAspectRatio="none"><path d="M320 250 L130 125 M320 250 L510 125 M320 250 L130 390 M320 250 L510 390"/><path className="signal-path" d="M130 125 L320 250 L510 125"/></svg></div><div className="hero-meta"><span>Product Engineering</span><span>AI Systems</span><span>Business Automation</span></div></section>
  <section id="services" className="section services-section"><SectionIntro label="CAPABILITIES" title="One studio. Complete systems." body="We design the interface, engineer the foundation, and connect the intelligence—so every layer works as one."/><div className="service-grid">{services.map(([Icon,code,title,text,tags])=><article className="service-card" key={title}><div className="card-top"><span>{code}</span><Icon size={24}/></div><h3>{title}</h3><p>{text}</p><div className="tag-row">{tags.map(t=><span key={t}>{t}</span>)}</div><a href="#contact">Explore capability <ArrowRight size={15}/></a></article>)}</div></section>
  <section id="systems" className="section dark-section build-system"><SectionIntro label="WHAT WE BUILD" title="Not isolated features. Connected business systems."/><div className="architecture"><div className="arch-line"/>{[[Globe2,"EXPERIENCE","Web / mobile"],[Database,"FOUNDATION","Data / backend"],[BrainCircuit,"INTELLIGENCE","Models / RAG"],[Bot,"AGENTS","Reason / act"],[Workflow,"AUTOMATION","Systems / people"],[Check,"OUTCOME","Work completed"]].map(([Icon,t,s],i)=>{const I=Icon as typeof Globe2;return <div key={t as string} className={`arch-node ${i===0?"active":""} ${i===5?"outcome":""}`}><I/><span>{t as string}</span><small>{s as string}</small></div>})}</div></section>
  <section className="section agent-section"><SectionIntro label="AGENT SYSTEMS" title="Give repetitive work to systems that can think and act." body="Select an agent to see how context becomes action—with explicit checkpoints and human control."/><div className="agent-console"><div className="agent-list" role="tablist">{agents.map(([name,Icon],i)=><button key={name} className={agent===i?"selected":""} onClick={()=>setAgent(i)} role="tab" aria-selected={agent===i}><Icon size={18}/><span>{name}</span><small>{String(i+1).padStart(2,"0")}</small></button>)}</div><div className="agent-flow"><div className="console-head"><span><i/> {agents[agent][0].toUpperCase()} / ACTIVE</span><span>CONTROLLED AUTONOMY</span></div><div className="thinking-orbs"><i/><i/><i/></div><div className="flow-steps">{agents[agent][2].map((step,i)=><div className="flow-step" key={step}><span>{i<4?<Check size={13}/>:<ArrowRight size={13}/>}</span><div><small>STEP {String(i+1).padStart(2,"0")}</small><strong>{step}</strong></div>{i<4&&<i/>}</div>)}</div></div></div></section>
  <section className="section voice-section"><div className="voice-copy"><SectionIntro label="VOICE AI" title="Speak. Understand. Think. Act." body="Voice agents that listen naturally, use the right tools, and complete real work—from qualification to scheduling and support."/><a className="text-link" href="#contact">Build a Voice Agent <ArrowUpRight size={16}/></a></div><div className="voice-visual"><div className="voice-status"><span><i/> LIVE CONVERSATION</span><small>00:24</small></div><div className="waveform">{[22,48,75,38,92,58,30,84,55,28,66,96,44,72,35,82,51,25,61,88,42,70,32,56].map((h,i)=><i key={i} style={{height:`${h}%`,animationDelay:`${i*.06}s`}}/>)}</div><div className="voice-steps"><span className="done">Signal</span><span className="done">Intent</span><span className="active">Reason</span><span>Action</span></div></div></section>
  <section className="section automation-section"><SectionIntro label="AUTOMATION" title="Turn fragmented steps into one intelligent flow."/><div className="workflow-canvas"><div className="workflow-line"/>{[[Zap,"01","Trigger","New lead"],[Bot,"02","AI Agent","Enrich & qualify"],[Network,"03","Decision","Route by fit"],[Database,"04","CRM","Update record"],[Check,"05","Approval","Human control"]].map(([Icon,n,t,s],i)=>{const I=Icon as typeof Zap;return <div key={t as string} className={`workflow-node ${i===1?"hot":""}`}><I/><small>{n as string}</small><strong>{t as string}</strong><span>{s as string}</span></div>})}</div></section>
  <section id="work" className="section work-section"><SectionIntro label="SELECTED BUILDS" title="Proof of capability, without invented proof." body="Until public client work is released, these clearly labeled concepts demonstrate the systems we can design and engineer."/><div className="work-grid"><article className="project-card project-large"><span className="project-type">INTERNAL PROTOTYPE</span><div className="project-art dashboard-art"><div className="art-sidebar"/><div className="art-panels"><i/><i/><i/></div><div className="art-chart"/></div><div className="project-info"><div><h3>Operations command center</h3><p>A unified workspace for teams, approvals, automations, and live business signals.</p></div><ArrowUpRight/></div></article><article className="project-card"><span className="project-type">PRODUCT EXPERIMENT</span><div className="project-art mobile-art"><div className="phone-frame"><i/><b/><span/></div><div className="phone-frame second"><i/><b/><span/></div></div><div className="project-info"><div><h3>Intelligent field service</h3><p>Mobile workflows with scheduling, voice capture, and automated reporting.</p></div><ArrowUpRight/></div></article></div></section>
  <section id="process" className="section process-section"><SectionIntro label="PROCESS" title="From ambiguity to operating software."/><div className="process-list">{process.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section id="about" className="section principles-section"><SectionIntro label="WHY SPARKV" title="Engineering discipline. Applied intelligence."/><div className="principles">{[["01","Engineering first","Systems designed for production, not prototypes that collapse under real use."],["02","AI where it matters","We use AI when it improves a decision, removes work, or creates a better experience."],["03","Built around the business","Technology should adapt to the workflow—not force the workflow to adapt to it."],["04","End to end","Strategy, product, engineering, intelligence, integration, deployment, and improvement."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="tech-strip">{["React","Next.js","Node.js","Python","PostgreSQL","AWS","OpenAI","Docker"].map(x=><span key={x}>{x}</span>)}</div></section>
  <section id="contact" className="section contact-section"><div className="contact-copy"><p className="section-label"><span/> START A PROJECT</p><h2>Have something worth building?</h2><p>Tell us what you’re trying to build, automate, or improve. We’ll turn the idea into a technical path forward.</p><div className="contact-note"><Sparkles size={18}/><span>No hard sell. Just a focused conversation about the problem and the strongest way to solve it.</span></div></div><form className="intake" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="form-success" role="status"><span><Check/></span><h3>Project brief captured.</h3><p>This demo validates the experience. Connect a secure form provider to deliver submissions in production.</p><button type="button" className="button button-dark" onClick={()=>{setSent(false);setFormStep(0)}}>Start another</button></div>:<><div className="form-progress"><span>PROJECT INTAKE</span><small>STEP {formStep+1} / 2</small><i><b style={{width:formStep?"100%":"50%"}}/></i></div>{formStep===0?<div className="form-panel"><label>What are you looking to build?</label><div className="project-types">{["Website","Web App","Mobile App","AI Agent","Voice Agent","Automation","AI System","Other"].map(x=><label key={x}><input type="radio" name="type" value={x} required/><span>{x}</span></label>)}</div><button type="button" className="button button-dark" onClick={()=>setFormStep(1)}>Continue <ArrowRight size={17}/></button></div>:<div className="form-panel fields"><label>Name<input name="name" required placeholder="Your name"/></label><label>Work email<input name="email" required type="email" placeholder="you@company.com"/></label><label className="full">What are you trying to build?<textarea name="brief" required rows={4} placeholder="The problem, current workflow, and what a successful outcome looks like…"/></label><div className="form-buttons"><button type="button" className="back" onClick={()=>setFormStep(0)}>Back</button><button className="button button-dark">Send Project Brief <ArrowUpRight size={17}/></button></div></div>}</>}</form></section>
  <footer><div className="footer-main"><div><SparkVLogo/><p>Software. AI. Automation.<br/>Built for what’s next.</p></div><div><strong>Services</strong><a href="#services">Software</a><a href="#services">Mobile</a><a href="#services">AI & Automation</a><a href="#services">Voice AI</a></div><div><strong>Company</strong><a href="#work">Work</a><a href="#process">Process</a><a href="#about">About</a><a href="#contact">Contact</a></div><a href="#top" className="back-top">Back to top <ArrowUpRight/></a></div><div className="footer-bottom"><span>© 2026 SparkV. All rights reserved.</span><span>PRIVACY · TERMS</span></div></footer>
 </main>
}
