"use client";
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { ArrowRight, ArrowUpRight, BarChart3, Bot, BrainCircuit, CalendarDays, Check, ChevronDown, Cloud, Code2, CreditCard, Database, FileSearch, Globe2, Inbox, Layers3, LockKeyhole, Megaphone, Menu, MessageSquareText, Mic2, Moon, Network, PhoneCall, Send, Smartphone, Sparkles, Sun, UploadCloud, Users, WandSparkles, Workflow, X, Zap } from "lucide-react";
import { SparkVLogo } from "@/components/sparkv-logo";
import { SparkVAgent } from "@/components/sparkv-agent";

const services = [
  [Code2,"01","Software Development","Web products, SaaS platforms, internal tools, APIs, and backend systems engineered to last.",["Web apps","SaaS","APIs"]],
  [Smartphone,"02","Mobile Development","Purpose-built iOS, Android, and cross-platform experiences backed by resilient systems.",["iOS","Android","Cross-platform"]],
  [BrainCircuit,"03","AI & Automation","AI copilots, RAG, document intelligence, and workflows connected to the tools you already use.",["RAG","Workflows","AI systems"]],
  [Bot,"04","AI Agents","Specialized agents that research, support, qualify, coordinate, and execute with human oversight.",["Sales","Support","Research"]],
  [Mic2,"05","Voice AI","Natural voice agents for reception, qualification, scheduling, and customer operations.",["Inbound","Outbound","Support"]],
  [MessageSquareText,"06","Social AI","Intelligent content, publishing, engagement, and lead workflows without brittle busywork.",["Content","Leads","Publishing"]],
] as const;
const agents = [
  ["Sales Agent",Zap,["Lead captured","Account researched","Qualified","CRM updated","Follow-up drafted"]],
  ["Research Agent",BrainCircuit,["Brief received","Sources searched","Evidence ranked","Findings synthesized","Report delivered"]],
  ["Support Agent",MessageSquareText,["Request understood","Context retrieved","Action selected","Issue resolved","Record updated"]],
  ["Voice Agent",PhoneCall,["Call connected","Intent detected","Tools invoked","Appointment booked","Summary sent"]],
] as const;
const processSteps = [["01","Discover","We map the business goal, constraints, users, and systems before choosing the technology."],["02","Design","We turn the problem into a clear product and technical architecture."],["03","Build","Small, testable releases keep quality visible and decisions reversible."],["04","Integrate","We connect data, APIs, AI models, and the tools your team already relies on."],["05","Launch","Production readiness includes security, observability, performance, and handoff."],["06","Improve","We learn from real usage, remove friction, and extend what creates value."]];
const PHASES=["INPUT","REASONING","REASONING","ACTION","OUTCOME"];
function Words({text}:{text:string}){return <>{text.split(" ").map((w,i)=><span className="hw" style={{"--i":i} as React.CSSProperties} key={i}>{w}</span>)}</>}
function HeroClock(){const [t,setT]=useState("");useEffect(()=>{const f=()=>setT(new Date().toLocaleTimeString("en-GB"));f();const id=setInterval(f,1000);return()=>clearInterval(id)},[]);return <span suppressHydrationWarning>{t||"--:--:--"}</span>}
function SectionIntro({label,title,body}:{label:string;title:string;body?:string}){return <div className="section-intro"><p className="section-label"><span/>{label}</p><h2>{title}</h2>{body&&<p>{body}</p>}</div>}

export function Homepage(){
 const [dark,setDark]=useState(true),[menu,setMenu]=useState(false),[agent,setAgent]=useState(0),[formStep,setFormStep]=useState(0),[sent,setSent]=useState(false),[projectType,setProjectType]=useState(""),[submitting,setSubmitting]=useState(false),[formError,setFormError]=useState(""),[tick,setTick]=useState(0);
 useEffect(()=>{const s=localStorage.getItem("sparkv-theme"),v=s?s==="dark":matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.dataset.theme=v?"dark":"light";document.documentElement.style.colorScheme=v?"dark":"light";queueMicrotask(()=>setDark(v))},[]);
 useEffect(()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const nodes=document.querySelectorAll(".section-intro,.service-card,.command-dashboard,.publish-pipeline,.approval-flow article,.catalog-grid article,.engineering-points>div,.production-feature,.manufacturing-visual,.project-card,.process-list article,.principles article,.faq-list details,.solution-grid article,.workflow-node,.arch-node,.venture-example,.contact-note,.intake");nodes.forEach(n=>n.classList.add("motion-observe"));const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");io.unobserve(e.target)}}),{threshold:.1,rootMargin:"0px 0px -8% 0px"});nodes.forEach(n=>io.observe(n));return()=>io.disconnect()},[]);
 useEffect(()=>{const h=document.querySelector(".site-header");const onScroll=()=>h?.classList.toggle("is-scrolled",window.scrollY>24);onScroll();window.addEventListener("scroll",onScroll,{passive:true});const links=document.querySelectorAll<HTMLAnchorElement>(".desktop-nav a");const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(l=>l.classList.toggle("active",l.hash==="#"+e.target.id))}),{rootMargin:"-45% 0px -50% 0px"});["services","systems","work","process","about"].forEach(id=>{const n=document.getElementById(id);if(n)io.observe(n)});const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setMenu(false)};window.addEventListener("keydown",onKey);return()=>{window.removeEventListener("scroll",onScroll);window.removeEventListener("keydown",onKey);io.disconnect()}},[]);
 useEffect(()=>{const hero=document.querySelector(".hero");if(!hero)return;const io=new IntersectionObserver(([e])=>hero.classList.toggle("hero-paused",!e.isIntersecting));io.observe(hero);return()=>io.disconnect()},[]);
 useEffect(()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches){queueMicrotask(()=>setTick(4));return}const el=document.querySelector(".agent-console");let vis=false;const io=new IntersectionObserver(([e])=>{vis=e.isIntersecting});if(el)io.observe(el);const id=setInterval(()=>{if(vis)setTick(t=>(t+1)%6)},1400);return()=>{clearInterval(id);io.disconnect()}},[agent]);
 const toggleTheme=()=>{const v=!dark;setDark(v);localStorage.setItem("sparkv-theme",v?"dark":"light");document.documentElement.dataset.theme=v?"dark":"light";document.documentElement.style.colorScheme=v?"dark":"light"};
 async function submitProject(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setFormError("");setSubmitting(true);
  const form=new FormData(e.currentTarget);
  try{
   const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectType,name:form.get("name"),email:form.get("email"),brief:form.get("brief"),companyWebsite:form.get("companyWebsite")})});
   const result=await response.json() as {error?:string};
   if(!response.ok)throw new Error(result.error||"We could not send your project brief.");
   setSent(true);
  }catch(error){setFormError(error instanceof Error?error.message:"We could not send your project brief.")}
  finally{setSubmitting(false)}
 }
 return <main className={dark?"theme-dark":"theme-light"}><div className="scroll-progress" aria-hidden="true"/>
  <header className="site-header"><a href="#top" className="brand" aria-label="SparkV home"><SparkVLogo/></a><nav className="desktop-nav"><a href="#services">Services</a><a href="#systems">Systems</a><a href="#work">Work</a><a href="#process">Process</a><a href="#about">About</a></nav><div className="header-actions"><button className="icon-button" onClick={toggleTheme} aria-label={dark?"Switch to light theme":"Switch to dark theme"}>{dark?<Sun size={16}/>:<Moon size={16}/>}</button><a href="#contact" className="header-cta">Start a project <ArrowUpRight size={15}/></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div><div className={`mobile-menu ${menu?"open":""}`}>{["services","systems","work","process","about","contact"].map(x=><a key={x} href={`#${x}`} onClick={()=>setMenu(false)}>{x[0].toUpperCase()+x.slice(1)}</a>)}</div></header>
  <section id="top" className="hero"><div className="hero-grid"/><div className="hero-glow"/><div className="hero-copy"><p className="eyebrow"><span/> SPARKV / SOFTWARE × AI × AUTOMATION</p><h1 aria-label="We build software that moves businesses forward."><span aria-hidden="true"><Words text="We build software that moves businesses"/><em><Words text="forward."/></em></span></h1><p className="hero-lede">From web and mobile products to AI agents, voice systems, and intelligent automation—SparkV turns complex ideas into production-ready technology.</p><p className="hero-audience">For founders, operators, and engineering teams who need working systems, not slideware.</p><div className="hero-actions"><a href="#contact" className="button button-primary">Start a Project <ArrowUpRight size={18}/></a><a href="#services" className="button button-ghost">Explore What We Build <ChevronDown size={17}/></a></div></div><div className="system-stage"><div className="stage-topline"><span>SYSTEM MODEL / ILLUSTRATIVE</span><HeroClock/></div><div className="system-ring ring-one"/><div className="system-ring ring-two"/><div className="system-core"><span>V</span><small>ORCHESTRATOR</small></div>{[["PRODUCT","Interface layer","node-product"],["INTELLIGENCE","Agent network","node-intel"],["AUTOMATION","Workflow engine","node-auto"],["OUTCOME","Business impact","node-outcome"]].map(x=><div key={x[0]} className={`system-node ${x[2]}`}><i/>{x[0]}<small>{x[1]}</small></div>)}<svg className="system-lines" viewBox="0 0 640 500" preserveAspectRatio="none"><path d="M320 250 L130 125 M320 250 L510 125 M320 250 L130 390 M320 250 L510 390"/><path className="signal-path" d="M130 125 L320 250 L510 125"/><circle className="packet pk1" r="3.5"/><circle className="packet pk2" r="3.5"/><circle className="packet pk3" r="3.5"/></svg></div><div className="hero-meta"><span>Product Engineering</span><span>AI Systems</span><span>Business Automation</span></div></section>
  <section id="services" className="section services-section"><SectionIntro label="CAPABILITIES" title="One studio. Complete systems." body="We design the interface, engineer the foundation, and connect the intelligence—so every layer works as one."/><div className="service-grid">{services.map(([Icon,code,title,text,tags])=><article className="service-card" key={title}><div className="card-top"><span>{code}</span><Icon size={24}/></div><h3>{title}</h3><p>{text}</p><div className="tag-row">{tags.map(t=><span key={t}>{t}</span>)}</div><a href="#contact">Explore capability <ArrowRight size={15}/></a></article>)}</div></section>
  <section className="section command-section"><div className="command-heading"><SectionIntro label="GROWTH COMMAND CENTER" title="Every channel. Every conversation. One intelligent workspace." body="Run social publishing, paid media, customer conversations, campaigns, bookings, and agent operations from one dashboard—or choose only the modules your team needs."/><div className="offer-switch"><span>ONE PLATFORM</span><i/> <span>INDIVIDUAL MODULES</span></div></div><div className="command-dashboard"><aside className="dash-rail"><SparkVLogo/><nav>{[[BarChart3,"Overview"],[Megaphone,"Campaigns"],[Inbox,"Inbox"],[Send,"Publishing"],[Bot,"Agents"],[Users,"Audiences"]].map(([Icon,label],i)=>{const I=Icon as typeof BarChart3;return <span className={i===0?"on":""} key={label as string}><I/>{label as string}</span>})}</nav><div className="rail-user"><i/>KG</div></aside><div className="dash-main"><div className="dash-head"><div><small>GOOD MORNING</small><h3>Growth overview</h3></div><button>Last 30 days <ChevronDown/></button></div><div className="metric-row"><article><small>REACH</small><strong>184.2K</strong><span className="metric-up">↗ 18.4%</span></article><article><small>ENGAGEMENT</small><strong>12.8K</strong><span className="metric-up">↗ 7.2%</span></article><article><small>CONVERSATIONS</small><strong>3,146</strong><span>Across 6 channels</span></article><article><small>BOOKINGS</small><strong>284</strong><span className="metric-up">↗ 11.6%</span></article></div><div className="dash-content"><div className="reach-chart"><div className="panel-title"><span>Reach & engagement</span><small><i/>Organic <i/>Paid</small></div><div className="chart-bars">{[42,58,49,72,63,86,76,92,68,83,96,88].map((h,i)=><span key={i} style={{height:`${h}%`}}><i style={{height:`${Math.max(15,h-24)}%`}}/></span>)}</div><div className="chart-days"><span>SEP 01</span><span>SEP 08</span><span>SEP 15</span><span>SEP 22</span><span>SEP 28</span></div></div><div className="ai-insight"><div className="panel-title"><span><Sparkles/> AI INSIGHT</span><small>LIVE</small></div><p>Your short-form videos are driving <strong>2.4× more qualified conversations</strong> than static posts this week.</p><div className="insight-action"><span>Shift 12% of the awareness budget to top-performing video audiences.</span><button>Review action <ArrowRight/></button></div></div><div className="channel-health"><div className="panel-title"><span>Channel health</span><small>ALL SYSTEMS</small></div>{[["IG","Instagram","Connected"],["WA","WhatsApp","Connected"],["TG","Telegram","Connected"],["SMS","SMS / RCS","Ready"]].map(x=><div key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span><i/></div>)}</div></div></div></div></section>
  <section className="section publish-section"><div className="publish-copy"><SectionIntro label="PUBLISH ONCE" title="One upload becomes a complete cross-channel campaign." body="Stop rebuilding the same post for every platform. SparkV can turn one source asset into channel-ready content, approvals, conversations, and measurable follow-through."/><div className="publish-benefits"><span><Check/>Platform-specific titles, captions, descriptions, and formats</span><span><Check/>Scheduled publishing to every channel you approve</span><span><Check/>Comment and inbox handling with human escalation</span><span><Check/>Performance insights that improve the next campaign</span></div></div><div className="publish-pipeline"><div className="upload-card"><UploadCloud/><strong>Drop one video</strong><small>source-reel.mp4 · 84 MB</small><span><i/></span></div><div className="pipeline-arrow"><ArrowRight/></div><div className="content-engine"><div className="engine-orb"><WandSparkles/></div><strong>Content engine</strong><small>Adapting voice, format & metadata</small><div className="engine-progress"><i/></div></div><div className="pipeline-arrow"><ArrowRight/></div><div className="platform-stack">{[["IG","Instagram","Ready"],["YT","YouTube","Ready"],["LI","LinkedIn","Ready"],["TK","TikTok","Ready"]].map(x=><div key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>Custom copy generated</small></span><i>{x[2]}</i></div>)}</div></div></section>
  <section className="section creator-loop"><SectionIntro label="CREATIVE APPROVAL LOOP" title="Create, review, refine, and publish—from the chat you already use." body="A staged workflow keeps humans in control while removing repetitive production work."/><div className="approval-flow">{[["01","Generate","Create thumbnail options and channel assets from the approved brand system."],["02","Review","Send previews to WhatsApp or Telegram for approval."],["03","Refine","Reply by text or voice: “make the headline bolder and use the second image.”"],["04","Approve","Choose the final asset with one tap, then schedule or publish everywhere."],["05","Expand","Next phase: generate complete niche-specific videos for review before publishing."]].map((x,i)=><article key={x[0]} className={i===2?"highlight":""}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p>{i<4&&<ArrowRight/>}</article>)}</div></section>
  <section className="section channel-agents"><div className="agents-copy"><SectionIntro label="CONVERSATIONAL AGENTS" title="Always-on agents for every important channel." body="Deploy one agent across channels or use specialized agents with their own knowledge, tools, guardrails, and escalation rules."/><a href="#contact" className="button button-primary">Design Your Agent System <ArrowUpRight/></a></div><div className="agent-orbit"><div className="orbit-core"><Bot/><span>SPARKV<br/>AGENT LAYER</span></div>{[[MessageSquareText,"WhatsApp","Qualification · support"],[Send,"Instagram DM","Engage · convert"],[PhoneCall,"Voice calls","Answer · book"],[Smartphone,"SMS / RCS","Notify · follow up"],[Inbox,"Unified inbox","Route · resolve"]].map((x,i)=>{const I=x[0] as typeof Bot;return <div className={`orbit-item orbit-${i+1}`} key={x[1] as string}><I/><span><strong>{x[1] as string}</strong><small>{x[2] as string}</small></span></div>})}<div className="orbit-ring ring-a"/><div className="orbit-ring ring-b"/></div></section>
  <section className="section venture-section"><div className="venture-card"><p className="section-label"><span/> PRODUCT VENTURES & WHITE-LABEL PLATFORMS</p><h2>Bring the idea. We’ll build the business-ready platform behind it.</h2><p>Launching a service business, marketplace, or industry platform? SparkV can design and build the complete multi-tenant product, then hand it over so you can onboard your own customers, manage their accounts, and grow the business under your brand.</p><div className="venture-example"><div><small>EXAMPLE</small><strong>Event operations platform</strong><span>A branded system for an operator to onboard multiple event clients, manage teams, bookings, vendors, payments, permissions, and reporting from one product.</span></div><div className="tenant-diagram"><b>YOUR PLATFORM</b><span>CLIENT A</span><span>CLIENT B</span><span>CLIENT C</span></div></div><div className="venture-tags">{["Multi-tenant architecture","White-label branding","Client onboarding","Roles & permissions","Billing & usage","Admin operations","API integrations","Launch & handover"].map(x=><span key={x}>{x}</span>)}</div><a href="#contact" className="button button-primary">Turn Your Idea Into a Platform <ArrowUpRight/></a></div></section>
  <section className="section capability-catalog"><SectionIntro label="PLATFORM CAPABILITIES" title="Start focused. Expand into one operating system." body="Each capability can be delivered independently or connected into a larger customer engagement, marketing, AI, and operations platform."/><div className="catalog-grid">{[[Inbox,"Unified communications","Unified inbox with Telegram, exportable history, bulk messaging, templates, SMS, RCS, and consent-aware channel management."],[Workflow,"Journeys & automation","Visual chatbot flows, drip sequences, approvals, calendar booking, surveys, branching logic, and publishing."],[Users,"Audience & customer data","Contact imports, deduplication, segmentation, B2B/B2C audience discovery, CDP sources, and identity resolution."],[Megaphone,"Marketing & advertising","Compliant AI messaging, social publishing, ad insights, reach analysis, CRM connections, and campaign operations."],[WandSparkles,"AI creative workspaces","Voice, image, video, music, and Compose workspaces with multi-model comparison and approval loops."],[FileSearch,"Agents & intelligence","Channel agents, web scrapers, research workflows, structured exports, knowledge retrieval, and human escalation."],[PhoneCall,"Mobile call center","Agent availability, queues, live call operations, dispositions, follow-up, and performance visibility."],[CreditCard,"Commercial operations","Billing, price books, usage metering, invoices, payments, subscriptions, and account entitlements."],[CalendarDays,"Business integrations","CRM, advertising, calendar, payments, social channels, communications providers, and custom APIs."],[LockKeyhole,"Administration & support","Invitations, roles, permissions, sessions, account status, support tickets, onboarding, and setup guides."]].map(([Icon,t,d],i)=>{const I=Icon as typeof Inbox;return <article key={t as string}><span>{String(i+1).padStart(2,"0")}</span><I/><h3>{t as string}</h3><p>{d as string}</p></article>})}</div></section>
  <section id="systems" className="section dark-section build-system"><SectionIntro label="WHAT WE BUILD" title="Not isolated features. Connected business systems."/><div className="architecture"><div className="arch-line"/>{[[Globe2,"EXPERIENCE","Web / mobile"],[Database,"FOUNDATION","Data / backend"],[BrainCircuit,"INTELLIGENCE","Models / RAG"],[Bot,"AGENTS","Reason / act"],[Workflow,"AUTOMATION","Systems / people"],[Check,"OUTCOME","Work completed"]].map(([Icon,t,s],i)=>{const I=Icon as typeof Globe2;return <div key={t as string} className={`arch-node ${i===0?"active":""} ${i===5?"outcome":""}`}><I/><span>{t as string}</span><small>{s as string}</small></div>})}</div></section>
  <section className="section agent-section"><SectionIntro label="AGENT SYSTEMS" title="Give repetitive work to systems that can think and act." body="Select an agent to see how context becomes action—with explicit checkpoints and human control."/><div className="agent-console"><div className="agent-list" role="tablist">{agents.map(([name,Icon],i)=><button key={name} className={agent===i?"selected":""} onClick={()=>{setAgent(i);setTick(matchMedia("(prefers-reduced-motion: reduce)").matches?4:0)}} role="tab" aria-selected={agent===i}><Icon size={18}/><span>{name}</span><small>{String(i+1).padStart(2,"0")}</small></button>)}</div><div className="agent-flow"><div className="console-head"><span><i/> {agents[agent][0].toUpperCase()} / ACTIVE</span><span>CONTROLLED AUTONOMY</span></div><div className="thinking-orbs"><i/><i/><i/></div><div className="flow-steps" aria-label="Agent workflow steps">{agents[agent][2].map((step,i)=><div className={`flow-step${tick>i?" done":""}${tick===i?" active":""}`} key={step}><span>{tick>i?<Check size={13}/>:<ArrowRight size={13}/>}</span><div><small>{PHASES[i]}</small><strong>{step}</strong></div>{i<4&&<i/>}</div>)}</div></div></div></section>
  <section className="section voice-section"><div className="voice-copy"><SectionIntro label="VOICE AI" title="Speak. Understand. Think. Act." body="Voice agents that listen naturally, use the right tools, and complete real work—from qualification to scheduling and support."/><a className="text-link" href="#contact">Build a Voice Agent <ArrowUpRight size={16}/></a></div><div className="voice-visual"><div className="voice-status"><span><i/> LIVE CONVERSATION</span><small>00:24</small></div><div className="waveform">{[22,48,75,38,92,58,30,84,55,28,66,96,44,72,35,82,51,25,61,88,42,70,32,56].map((h,i)=><i key={i} style={{height:`${h}%`,animationDelay:`${i*.06}s`}}/>)}</div><div className="voice-steps"><span className="done">Signal</span><span className="done">Intent</span><span className="active">Reason</span><span>Action</span></div></div></section>
  <section className="section automation-section"><SectionIntro label="AUTOMATION" title="Turn fragmented steps into one intelligent flow."/><div className="workflow-canvas"><div className="workflow-line"/>{[[Zap,"01","Trigger","New lead"],[Bot,"02","AI Agent","Enrich & qualify"],[Network,"03","Decision","Route by fit"],[Database,"04","CRM","Update record"],[Check,"05","Approval","Human control"]].map(([Icon,n,t,s],i)=>{const I=Icon as typeof Zap;return <div key={t as string} className={`workflow-node ${i===1?"hot":""}`}><I/><small>{n as string}</small><strong>{t as string}</strong><span>{s as string}</span></div>})}</div></section>
  <section className="section engineering-section"><div className="engineering-copy"><SectionIntro label="SOFTWARE ENGINEERING" title="A strong foundation before the intelligence layer." body="AI is most useful when the software beneath it is secure, observable, and designed around real operations. We build both."/><div className="engineering-points">{[[Layers3,"Product architecture","Clear boundaries between interface, services, data, and integrations."],[LockKeyhole,"Authentication & security","Identity, permissions, validation, and safe server-side boundaries."],[Cloud,"Infrastructure","Deployment, environments, monitoring, and reliable delivery pipelines."],[BarChart3,"Analytics & operations","Useful product signals, auditability, and tools teams can operate."]].map(([Icon,t,d])=>{const I=Icon as typeof Layers3;return <div key={t as string}><I/><span><strong>{t as string}</strong><small>{d as string}</small></span></div>})}</div></div><div className="code-window"><div className="window-bar"><span/><span/><span/><small>system.architecture.ts</small></div><pre><code><b>01</b>  product.experience<br/><b>02</b>  ├─ web + mobile<br/><b>03</b>  ├─ identity + permissions<br/><b>04</b>  ├─ api + services<br/><b>05</b>  ├─ data + observability<br/><b>06</b>  └─ intelligence<br/><b>07</b>     ├─ retrieval<br/><b>08</b>     ├─ agents<br/><b>09</b>     └─ automation</code></pre><div className="code-status"><span><i/> PRODUCTION READY</span><span>ALL SYSTEMS CONNECTED</span></div></div></section>
  <section className="section manufacturing-section"><div className="manufacturing-head"><SectionIntro label="PRODUCTION MANAGEMENT" title="From quote to service. Every job, stage, document, and decision in one cloud system." body="We study how your company actually operates, then build production software around that process—not the other way around. Teams get one live source of truth, accessible anywhere, with nothing lost between spreadsheets, inboxes, and departments."/><a href="#contact" className="button button-primary">Build Your Operations Platform <ArrowUpRight/></a></div><div className="manufacturing-visual"><div className="visual-sheen"/><div className="manufacturing-image" role="img" aria-label="SparkV production control center showing manufacturing schedule, job stages, role permissions, cloud records, inventory and alerts"/></div><div className="production-flow">{["Quote","Backlog","Build","Prefab","Paint","Outsource","Shipping","VIN","Service","Parts"].map((x,i)=><div key={x} className={i===3?"current":""}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong>{i<9&&<ArrowRight/>}</div>)}</div><div className="production-features"><article className="production-feature"><Workflow/><h3>Drag-and-drop scheduling</h3><p>Move work between production lines, dates, teams, and stages while dependencies and downstream plans stay visible.</p></article><article className="production-feature"><Cloud/><h3>Complete cloud record</h3><p>Quotes, build files, photos, quality records, VINs, shipping documents, service history, and parts are retrievable anywhere.</p></article><article className="production-feature"><LockKeyhole/><h3>Role-based access control</h3><p>Give administrators, production managers, planners, floor teams, quality, service, and customers only the access they need.</p></article><article className="production-feature"><BarChart3/><h3>Operations control center</h3><p>Track status, bottlenecks, late work, inventory, outsourcing, alerts, and performance without chasing manual updates.</p></article></div><div className="manufacturing-outcomes"><span><Check/>Fewer missed handoffs</span><span><Check/>Faster information retrieval</span><span><Check/>Live accountability</span><span><Check/>One operational history</span><span><Check/>Accessible from anywhere</span></div></section>
  <section className="section mobile-showcase"><div className="mobile-visual"><div className="device device-one"><div className="device-top"/><div className="device-screen"><small>TODAY</small><h4>Field operations</h4><div className="mini-map"><i/><i/><i/></div><div className="mini-row"><span/><b/></div><div className="mini-row"><span/><b/></div></div></div><div className="device device-two"><div className="device-top"/><div className="device-screen dark-screen"><small>AI ASSISTANT</small><div className="assistant-orb"/><p>Three visits are ready for review.</p><button>Review schedule</button></div></div></div><div className="mobile-copy"><SectionIntro label="MOBILE PRODUCTS" title="Native-feeling experiences. Connected to the business." body="We create focused mobile products for customers and field teams, with the backend, authentication, offline behavior, and AI workflows they depend on."/><div className="platform-row"><span>iOS</span><span>Android</span><span>Cross-platform</span><span>Mobile backend</span></div><a href="#contact" className="text-link">Build a Mobile Product <ArrowUpRight size={16}/></a></div></section>
  <section className="section solutions-section"><SectionIntro label="SOLUTIONS" title="Technology shaped around the operating problem." body="The same engineering system can serve very different outcomes. We start with the workflow and design the right combination of product, AI, and automation."/><div className="solution-grid">{[["Customer operations","AI support, voice reception, scheduling, knowledge retrieval, and human escalation."],["Revenue workflows","Lead capture, enrichment, qualification, outreach support, CRM updates, and follow-up."],["Internal operations","Approval flows, document processing, reporting, data synchronization, and team tools."],["AI-powered products","Customer-facing experiences built around retrieval, generation, agents, and safe tool use."],["Modernization","Replace manual processes and fragile spreadsheets with reliable, purpose-built software."],["System integration","Connect APIs, databases, SaaS tools, and internal systems into one dependable flow."]].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{x[0]}</h3><p>{x[1]}</p><ArrowUpRight/></article>)}</div></section>
  <section id="work" className="section work-section"><SectionIntro label="SELECTED BUILDS" title="Proof of capability, without invented proof." body="Until public client work is released, these clearly labeled concepts demonstrate the systems we can design and engineer."/><div className="work-grid"><article className="project-card project-large"><span className="project-type">INTERNAL PROTOTYPE</span><div className="project-art dashboard-art"><div className="art-sidebar"/><div className="art-panels"><i/><i/><i/></div><div className="art-chart"/></div><div className="project-info"><div><h3>Operations command center</h3><p>A unified workspace for teams, approvals, automations, and live business signals.</p></div><ArrowUpRight/></div></article><article className="project-card"><span className="project-type">PRODUCT EXPERIMENT</span><div className="project-art mobile-art"><div className="phone-frame"><i/><b/><span/></div><div className="phone-frame second"><i/><b/><span/></div></div><div className="project-info"><div><h3>Intelligent field service</h3><p>Mobile workflows with scheduling, voice capture, and automated reporting.</p></div><ArrowUpRight/></div></article></div></section>
  <section id="process" className="section process-section"><SectionIntro label="PROCESS" title="From ambiguity to operating software."/><div className="process-list">{processSteps.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section id="about" className="section principles-section"><SectionIntro label="WHY SPARKV" title="Engineering discipline. Applied intelligence."/><div className="principles">{[["01","Engineering first","Systems designed for production, not prototypes that collapse under real use."],["02","AI where it matters","We use AI when it improves a decision, removes work, or creates a better experience."],["03","Built around the business","Technology should adapt to the workflow—not force the workflow to adapt to it."],["04","End to end","Strategy, product, engineering, intelligence, integration, deployment, and improvement."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="tech-strip">{["React","Next.js","Node.js","Python","PostgreSQL","AWS","OpenAI","Docker"].map(x=><span key={x}>{x}</span>)}</div></section>
  <section className="section faq-section"><SectionIntro label="COMMON QUESTIONS" title="Clarity before complexity."/><div className="faq-list">{[["What kind of projects are a strong fit?","Custom software, web or mobile products, AI agents, voice systems, and automations where the business process matters as much as the interface."],["Can SparkV improve an existing system?","Yes. We can assess the current architecture, isolate the highest-value bottleneck, and modernize incrementally instead of forcing a complete rebuild."],["How do you decide where AI belongs?","We begin with the decision or task. AI belongs where probabilistic reasoning creates value; deterministic rules remain deterministic. Human review stays where risk requires it."],["Can you integrate with our current tools?","Most modern platforms expose APIs or webhooks. We map the available interfaces, security constraints, and failure modes before recommending an integration approach."],["What happens after launch?","Launch is the beginning of real evidence. We monitor system behavior, learn from usage, fix friction, and extend the product around demonstrated value." ]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section id="contact" className="section contact-section"><div className="contact-copy"><p className="section-label"><span/> START A PROJECT</p><h2>Have something worth building?</h2><p>Tell us what you’re trying to build, automate, or improve. We’ll turn the idea into a technical path forward.</p><div className="contact-note"><Sparkles size={18}/><span>No hard sell. Just a focused conversation about the problem and the strongest way to solve it.</span></div></div><form className="intake" onSubmit={submitProject}>{sent?<div className="form-success" role="status"><span><Check/></span><h3>Project brief delivered.</h3><p>Thanks—SparkV received your project details and can follow up using the email you provided.</p><button type="button" className="button button-dark" onClick={()=>{setSent(false);setFormStep(0);setProjectType("")}}>Start another</button></div>:<><div className="form-progress"><span>PROJECT INTAKE</span><small>STEP {formStep+1} / 2</small><i><b style={{width:formStep?"100%":"50%"}}/></i></div>{formStep===0?<div className="form-panel"><label>What are you looking to build?</label><div className="project-types">{["Website","Web App","Mobile App","AI Agent","Voice Agent","Automation","AI System","Other"].map(x=><label key={x}><input type="radio" name="type" value={x} checked={projectType===x} onChange={()=>setProjectType(x)}/><span>{x}</span></label>)}</div>{formError&&<p className="form-error" role="alert">{formError}</p>}<button type="button" className="button button-dark" disabled={!projectType} onClick={()=>{if(projectType){setFormError("");setFormStep(1)}else setFormError("Choose a project type to continue.")}}>Continue <ArrowRight size={17}/></button></div>:<div className="form-panel fields"><input className="form-honeypot" name="companyWebsite" tabIndex={-1} autoComplete="off" aria-hidden="true"/><label>Name<input name="name" required minLength={2} maxLength={100} autoComplete="name" placeholder="Your name"/></label><label>Work email<input name="email" required type="email" maxLength={254} autoComplete="email" placeholder="you@company.com"/></label><label className="full">What are you trying to build?<textarea name="brief" required minLength={10} maxLength={5000} rows={4} placeholder="The problem, current workflow, and what a successful outcome looks like…"/></label>{formError&&<p className="form-error full" role="alert">{formError}</p>}<div className="form-buttons"><button type="button" className="back" disabled={submitting} onClick={()=>setFormStep(0)}>Back</button><button className="button button-dark" disabled={submitting}>{submitting?"Sending…":"Send Project Brief"} {!submitting&&<ArrowUpRight size={17}/>}</button></div></div>}</>}</form></section>
  <SparkVAgent/>
  <footer><div className="footer-main"><div><SparkVLogo/><p>Software. AI. Automation.<br/>Built for what’s next.</p></div><div><strong>Services</strong><a href="#services">Software</a><a href="#services">Mobile</a><a href="#services">AI & Automation</a><a href="#services">Voice AI</a></div><div><strong>Company</strong><a href="#work">Work</a><a href="#process">Process</a><a href="#about">About</a><a href="#contact">Contact</a></div><a href="#top" className="back-top">Back to top <ArrowUpRight/></a></div><div className="footer-bottom"><span>© 2026 SparkV. All rights reserved.</span><span>PRIVACY · TERMS</span></div></footer>
 </main>
}
