"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowUp, Bot, Check, MessageSquareText, Sparkles, X } from "lucide-react";

const knowledge = [
  { keys:["production","manufacturing","factory","quote","vin","schedule","rbac"], answer:"SparkV builds cloud production-management systems around your exact workflow—from quotes and backlog through build, prefab, paint, outsourcing, shipping, VIN assignment, service, and parts. These systems can include drag-and-drop scheduling, cloud records, inventory, alerts, dashboards, and role-based access control." },
  { keys:["social","reel","post","caption","thumbnail","publish"], answer:"SparkV can build a publish-once content system that adapts one upload for each selected social platform, generates channel-specific titles, descriptions, and captions, manages approvals in WhatsApp or Telegram, and coordinates publishing and comment workflows." },
  { keys:["whatsapp","instagram","sms","voice","agent","inbox"], answer:"SparkV offers WhatsApp, Instagram DM, SMS/RCS, voice-call, and unified-inbox agents. Each can work independently or share knowledge, tools, consent rules, escalation logic, and one operations dashboard." },
  { keys:["platform","multi-tenant","white label","business","idea","event"], answer:"Bring the idea and SparkV can build the complete business-ready platform behind it. That includes multi-tenant architecture, white-label branding, customer onboarding, subscriptions, billing, roles, admin operations, integrations, deployment, and handover so you can run the product under your own brand." },
  { keys:["ai","automation","rag","model"], answer:"SparkV designs practical AI systems: RAG and knowledge retrieval, agents, document processing, workflow automation, multi-model comparison, creative workspaces, research and scraping, approval loops, and safe human escalation." },
  { keys:["web","mobile","software","api","cloud"], answer:"SparkV builds websites, web applications, mobile products, SaaS platforms, internal tools, APIs, backend systems, authentication, databases, cloud infrastructure, analytics, and integrations—with AI added where it creates real operational value." },
  { keys:["price","cost","timeline","start","contact","project"], answer:"Every engagement depends on scope, integrations, security, and rollout needs. Use “Start a Project” to share the problem, current workflow, and desired outcome. SparkV will turn that into a focused technical path forward." },
];
const fallback="I can help with SparkV’s software development, production platforms, AI agents, social automation, voice systems, multi-tenant products, integrations, and project process. Try asking what SparkV could build for your business.";
function answerFor(input:string){const q=input.toLowerCase();let best={score:0,answer:fallback};for(const item of knowledge){const score=item.keys.filter(k=>q.includes(k)).length;if(score>best.score)best={score,answer:item.answer}}return best.answer}

export function SparkVAgent(){
 const [open,setOpen]=useState(false),[input,setInput]=useState(""),[messages,setMessages]=useState<{role:"agent"|"user";text:string}[]>([{role:"agent",text:"Hi—I'm the SparkV site guide. Ask me what we can build, automate, connect, or turn into a platform."}]);
 useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[open]);
 function send(e:FormEvent){e.preventDefault();const q=input.trim();if(!q)return;setMessages(m=>[...m,{role:"user",text:q},{role:"agent",text:answerFor(q)}]);setInput("")}
 return <div className={`site-agent ${open?"agent-open":""}`}><button className="agent-launcher" onClick={()=>setOpen(!open)} aria-label={open?"Close SparkV assistant":"Open SparkV assistant"} aria-expanded={open}>{open?<X/>:<><Bot/><i/></>}</button>{open&&<section className="agent-panel" aria-label="SparkV AI assistant"><header><div><span><Sparkles/> SPARKV AGENT</span><small><i/> Website knowledge active</small></div><button onClick={()=>setOpen(false)} aria-label="Close assistant"><X/></button></header><div className="agent-messages" role="log" aria-live="polite">{messages.map((m,i)=><div className={`agent-message ${m.role}`} key={i}>{m.role==="agent"&&<Bot/>}<p>{m.text}</p></div>)}</div><div className="agent-prompts">{["Production platform","Social automation","Channel agents"].map(x=><button key={x} onClick={()=>{setMessages(m=>[...m,{role:"user",text:x},{role:"agent",text:answerFor(x)}])}}>{x}</button>)}</div><form onSubmit={send}><MessageSquareText/><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about SparkV…" aria-label="Ask SparkV"/><button aria-label="Send question"><ArrowUp/></button></form><footer><Check/> Trained on the information on this website</footer></section>}</div>
}
